#!/usr/bin/env bash
# careful-coder build script
#
# Builds the .skill bundle from source files (SKILL.md + references/ + assets/)
# and writes a careful-coder.lock with sha256 hashes of every source file.
#
# Usage:
#   ./scripts/build.sh                 # builds in-place into the skill root
#   ./scripts/build.sh <output-dir>    # builds into <output-dir>/careful-coder.skill
#
# The lockfile lets the host detect drift between the .skill bundle and source.
# scripts/lint.py reads careful-coder.lock to verify the bundle is up-to-date.

set -euo pipefail

SKILL_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${1:-$SKILL_ROOT}"
SKILL_NAME="$(basename "$SKILL_ROOT")"

cd "$SKILL_ROOT"

# 1. Compute sha256 of every source file (SKILL.md, CHANGELOG.md, references/*.md, assets/**/*.md, scripts/*.{py,sh})
echo "==> Hashing source files..."
TMP_LOCK="$(mktemp)"
{
  echo "# careful-coder.lock"
  echo "# Auto-generated by scripts/build.sh — do not edit by hand."
  echo "# version: 1"
  echo ""
  echo "## Source file hashes (sha256)"
  echo ""
  # Stable order: alphabetic
  find SKILL.md CHANGELOG.md README.md LICENSE references assets scripts -type f \
    \( -name '*.md' -o -name '*.py' -o -name '*.sh' -o -name 'LICENSE' \) 2>/dev/null \
    | sort | while read -r f; do
      h=$(sha256sum "$f" | awk '{print $1}')
      echo "$h  $f"
    done
} > "$TMP_LOCK"

mv "$TMP_LOCK" "$SKILL_ROOT/careful-coder.lock"
echo "    wrote $SKILL_ROOT/careful-coder.lock"

# 2. Run lint to ensure consistency
echo "==> Running lint..."
python3 "$SKILL_ROOT/scripts/lint.py" --skill-root "$SKILL_ROOT"

# 3. Locate package_skill.py (search common install locations; user can override)
#
# Resolution order:
#   1. $SKILL_PACKAGER env var (explicit)
#   2. $HOME/.claude/skills/skill-creator/scripts/package_skill.py (default install)
#   3. $XDG_DATA_HOME/.claude/skills/... (XDG layout)
PACKAGER="${SKILL_PACKAGER:-}"
if [ -z "$PACKAGER" ]; then
  for cand in \
    "$HOME/.claude/skills/skill-creator/scripts/package_skill.py" \
    "${XDG_DATA_HOME:-$HOME/.local/share}/claude/skills/skill-creator/scripts/package_skill.py" ; do
    if [ -f "$cand" ]; then
      PACKAGER="$cand"
      break
    fi
  done
fi

if [ -z "$PACKAGER" ] || [ ! -f "$PACKAGER" ]; then
  echo "ERROR: package_skill.py not found." >&2
  echo "       Tried: \$SKILL_PACKAGER (unset or invalid); \$HOME/.claude/skills/skill-creator/scripts/package_skill.py" >&2
  echo "       Fix: install the skill-creator skill, OR set SKILL_PACKAGER=<full-path-to-package_skill.py> and re-run." >&2
  echo "       Source + lock are ready at $SKILL_ROOT but the .skill bundle was NOT generated." >&2
  exit 2
fi

echo "==> Packaging via $PACKAGER..."
PACKAGER_DIR="$(dirname "$(dirname "$PACKAGER")")"
cd "$PACKAGER_DIR"
python3 -m scripts.package_skill "$SKILL_ROOT" "$OUTPUT_DIR"

# 4. Append .skill bundle hash to lockfile so lint can verify the bundle is in sync with source
SKILL_BUNDLE="$OUTPUT_DIR/$SKILL_NAME.skill"
if [ -f "$SKILL_BUNDLE" ]; then
  BUNDLE_HASH=$(sha256sum "$SKILL_BUNDLE" | awk '{print $1}')
  {
    echo ""
    echo "## Bundle hash (sha256 of the .skill file)"
    echo ""
    echo "$BUNDLE_HASH  $SKILL_NAME.skill"
  } >> "$SKILL_ROOT/careful-coder.lock"
  echo "    appended bundle hash to lockfile"
fi

echo "==> Build complete."
echo "    .skill bundle:  $SKILL_BUNDLE"
echo "    lockfile:       $SKILL_ROOT/careful-coder.lock"
